// flow-typed signature: d8830d336b37c5a6018be7a00e05d973
// flow-typed version: <<STUB>>/@jedwards1211/eslint-config-flow_v^1.0.0/flow_v0.145.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@jedwards1211/eslint-config-flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@jedwards1211/eslint-config-flow' {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module '@jedwards1211/eslint-config-flow/index' {
  declare module.exports: $Exports<'@jedwards1211/eslint-config-flow'>
}
declare module '@jedwards1211/eslint-config-flow/index.js' {
  declare module.exports: $Exports<'@jedwards1211/eslint-config-flow'>
}
